* Media Tracker
** Introduction
   Media Tracker is a challenge application. As such,
   I wanted it to be of actual use for myself.
   Basically, I have a rather large collection
   of media I wish to track. Books, music, research
   papers, and more. This servervs as a general
   tracker that has an API as well as
   a front-end single-page app that uses the
   API itself.
** Requirements for this Project
*** API
    JSON / REST
*** Authenication
*** User modes
**** Admin
     Has access to everything.
**** User
     Can read everything, but only update and delete
     his own records.
**** Guest
     Read access only
*** Other Requirements
    # At least 2 different models
    # Models 1 to many relationship
    # Seeds files with at least one record of sample data for each model.
    # API documented!!!!
*** Looking to access
    # RoR
    # API Design / REST
    # OOP / Clean Code / SOLID
    # Testing!!!!
    # Web development (BONUS)
** Design
   I will use API Blueprint for JSON API Documentation.
   https://apiblueprint.org/documentation/tutorial.html
** Notes
*** Devise
    Some setup you must do manually if you haven't yet:

  1. Ensure you have defined default url options in your environments files. Here
     is an example of default_url_options appropriate for a development environment
     in config/environments/development.rb:

       config.action_mailer.default_url_options = { host: 'localhost', port: 3000 }

     In production, :host should be set to the actual host of your application.

  2. Ensure you have defined root_url to *something* in your config/routes.rb.
     For example:

       root to: "home#index"

  3. Ensure you have flash messages in app/views/layouts/application.html.erb.
     For example:

       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

  4. You can copy Devise views (for customization) to your app by running:

       rails g devise:views
