# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: media-tracker_development

test:
  <<: *default
  database: media-tracker_test

production:
  <<: *default
  database: media-tracker_production
  username: media-tracker
  password: <%= ENV['MEDIA-TRACKER_DATABASE_PASSWORD'] %>
